### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yohamta** [yohamta/donburi#5]
- [ ] tests: add more tests
- [ ] tests: testcov
- [ ] chore: automated test with GitHub Action
- [ ] chore: Update ebitengin version
